services:
  fastapi:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
      - ROOM_EXPIRE=300
      - MAX_MESSAGE_SIZE=4096
      - MAX_ROOM_GENERATION_ATTEMPTS=1000
    depends_on:
      - redis
    networks:
      - signaling-server-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: signaling-server-redis
    networks:
      - signaling-server-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: signaling-server-nginx
    depends_on:
      - fastapi
    ports:
      - "8080:80"  # Nginx listens on port 8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - signaling-server-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


networks:
  signaling-server-network:
    driver: bridge
